-- AlterTable
ALTER TABLE "Room" ADD COLUMN "name" TEXT NOT NULL DEFAULT 'Watch Party';
ALTER TABLE "Room" ADD COLUMN "playbackUpdatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "Room" ALTER COLUMN "videoId" DROP DEFAULT;
